name: Build mod

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Build with Gradle
        run: gradle build

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: fov-unlock-mod-jar
          path: build/libs/*.jar
